### ISSUE TITLE
New API with API Token

### ISSUE THREAD

**Issue by kki03** [mtrossbach/noah-mqtt#81]
Hi,
just stumbled uppon the possibility to create an API Token in the UI. 

![Image](https://github.com/user-attachments/assets/96053fdd-dee0-4061-9428-c9ffe5a54077)
After creating the Token I got an email with a link to the API documentation: https://www.showdoc.com.cn/2540838290984246/11292912972201443

I didn´t look into the details but at least it has an endpoint to fetch the latest data mentioning "The frequency of acquisition is once per minute." in the documentation.

Looks really promising at a first glance.

```
curl -X POST --location "https://openapi.growatt.com/v4/new-api/queryLastData?deviceSn=....&deviceType=noah" \
    -H "token: <token generated in ui>" \
    -H "Content-Type: application/x-www-form-urlencoded"
```

```json
{
  "code": 0,
  "data": {
    "noah": [
      {
        "deviceSn": "...",
        "datalogSn": "...",
        "time": 1740048177165,
        "isAgain": 0,
        "status": 1,
        "mpptProtectStatus": 0,
        "pdWarnStatus": 0,
        "pac": 261.0,
        "eacToday": 2.3,
        "eacMonth": 21.5,
        "eacYear": 21.5,
        "eacTotal": 21.5,
        "ppv": 0.0,
        "workMode": 0,
        "totalBatteryPackChargingStatus": 2,
        "totalBatteryPackChargingPower": -339,
        "batteryPackageQuantity": 2,
        "totalBatteryPackSoc": 77,
        "heatingStatus": 0,
        "faultStatus": 0,
        "battery1SerialNum": "...",
        "battery1Soc": 76,
        "battery1Temp": 9.0,
        "battery1WarnStatus": 0,
        "battery1ProtectStatus": 0,
        "battery2SerialNum": "...",
        "battery2Soc": 78,
        "battery2Temp": 7.0,
        "battery2WarnStatus": 0,
        "battery2ProtectStatus": 0,
        "battery3SerialNum": "",
        "battery3Soc": 0,
        "battery3Temp": 0.0,
        "battery3WarnStatus": 0,
        "battery3ProtectStatus": 0,
        "battery4SerialNum": "",
        "battery4Soc": 0,
        "battery4Temp": 0.0,
        "battery4WarnStatus": 0,
        "battery4ProtectStatus": 0,
        "settableTimePeriod": 5,
        "acCoupleWarnStatus": 0,
        "acCoupleProtectStatus": 0,
        "ctFlag": 0,
        "totalHouseholdLoad": 0.0,
        "householdLoadApartFromGroplug": 0.0,
        "onOffGrid": 0,
        "ctSelfPower": 0.0,
        "chargeSocLimit": 100,
        "dischargeSocLimit": 10,
        "pv1Voltage": 6.46,
        "pv1Current": 0.0,
        "pv1Temp": 7.6,
        "pv2Voltage": 5.71,
        "pv2Current": 0.05,
        "pv2Temp": 8.0,
        "systemTemp": 8.0,
        "maxCellVoltage": 3295.0,
        "minCellVoltage": 3290.0,
        "batteryCycles": 21,
        "batterySoh": 76,
        "pv3Voltage": 0.0,
        "pv3Current": 0.0,
        "pv3Temp": 0.0,
        "pv4Voltage": 0.0,
        "pv4Current": 0.0,
        "pv4Temp": 0.0,
        "battery1TempF": 48.2,
        "battery2TempF": 44.6,
        "battery3TempF": 32.0,
        "battery4TempF": 32.0
      }
    ]
  },
  "message": "SUCCESSFUL_OPERATION"
}
```

BR
Klaus

**Comment by ollibaer** [comment]
Hey Klaus, thanks for the tip. I successfully tested (SetPower) with Node-Red:

**1. Inject Node:**

**2. Function Node:**

msg.headers = {
    "token": "Your Token",
    "Content-Type": "application/x-www-form-urlencoded"
};
msg.payload = "deviceSn=Your_Device_SN&deviceType=noah&value=100";
return msg;

**3. HTTP Request Node:** 
Method POST, 
URL: https://openapi.growatt.com/v4/new-api/setPower, 
Return: parsed JSON object

**4. Debug Node**

Now, the Noah Power Output can be set. Cheers, Olli :-)

Next:
-Set the power on and off
-Set the upper limit of the discharge SOC 
-Set the lower discharge SOC limit
-Set the time period and mode
-Noah's latest detailed data.

**Comment by mtrossbach** [comment]
Thanks for sharing your findings and experiments with the new Growatt API.

I've also generated an API token and attempted to use the endpoints from the same documentation you linked. Unfortunately, I'm consistently receiving an empty device list when trying to retrieve my devices. When I attempt to access device information directly using the serial number, I get an "DEVICE_SN_DOES_NOT_HAVE_PERMISSION" error. I even tried to completely remove and re-add my device to the account and rotate the API keys.

I've also reached out to Growatt Service via email, but haven't received a response yet. Additionally, I've applied for an OSS account as suggested, hoping to gain access to potentially more functional APIs. However, my application is still pending approval.

Therefore, at this time, I am unable to test the APIs effectively. It seems there might be some underlying issues with the API access or documentation that are preventing me from retrieving device data correctly.

Let's keep each other updated on our progress.

Best regards,
Markus

**Comment by rf7e** [comment]
I testet new Growatt API yesterday by creating request manually in Firefox "tools for web developers"
I'm not amused about the "Access Frequency Limits" of about 1-5 minutes 😲😡🤢
but i think, THIS (noah-mqtt issues)  is not the place to discuss it. 🤷🏻‍♂️

So I have some things to remark:
* the current noah-mqtt is small and it works (mostly😉)
* from time to time Growatt thinks it is useful to implement some pits 😣 
* we actually get ~16 values: enough to handle Noah
* with new api there are too many values (if we get them all) so an interface would hardly run on older slower hardware

in my opinion noah-mqtt should stay as it is: useful, small, easy to install
i love the way and speed how errors are fixed by Markus and others. THX for that 🙂

**Comment by msmthng** [comment]
the biggest disadvantage from the app api implementation is the getting blocked topic. i am still not able to use the shine app in my home notework, since the ip adress is still blocked.

**Comment by mtrossbach** [comment]
Thank you very much!

My personal goal would probably be using the Web-APIs for (at least status-) data fetching (as they seem to pollable more often than once a minute) and using the OSS API (API Token) for setting parameters. (The authentication flow for the app apis is ... let's say ... interessting and error-prone)

But still I'm not able to use these OSS APIs myself ... my devices doesn't show up and Growatt still not responded to my support request and to my request to have an Installer OSS account :-(

**Comment by mtrossbach** [comment]
Okay, just go the message from Growatt for my OSS Installer account: rejected, as they could not find any information about my Installer Company online :-/

**Comment by msmthng** [comment]
> Okay, just go the message from Growatt for my OSS Installer account: rejected, as they could not find any information about my Installer Company online :-/

Strange, it seems that they didn't check anything for my application.

**Comment by ssunny1081** [comment]
Tried as well, but same result DEVICE_SN_DOES_NOT_HAVE_PERMISSION. Application for an Installer Account was rejected asking for my "Gewerbeschein". It is possible to create an Electrician Account but seems useless it is only a royalty Programm for UK where you can select points for selling Stuff.

@ollibaer What has to be done with the Installer account, did you link it the user and than somewhat approve the token? 
Maybe I could ask my Dealer to do it for me.

**Comment by justinh998** [comment]
Hello, 
I can actually use all api entpoints with the api key I generated at openapi.growatt.com. I have also integrated the whole thing as a test as rest sensors in Home Assitant but the api has a huge disadvantage that makes it impractical. you can only retrieve data every 60 seconds, if you try it more often you get an error.

I think 60 seconds is very slow, especially since you can get data almost to the second even on the openapi website.

With all other Growatt products (e.g. inverters) you can only retrieve data every 5 minutes.

**Comment by ssunny1081** [comment]
Just tried again https://openapi.growatt.com/v4/new-api/queryLastData but still getting, DEVICE_SN_DOES_NOT_HAVE_PERMISSION

Which EndPoints are you calling?

I could not get an OSS account even after direct contact to the Support -> APIs only for trained experts, like everyone with a Gewerbe would be..

**Comment by ericrector** [comment]
Is "https://openapi.growatt.com/v4/new-api/queryLastData" your complete location?

If yes, you need to add "?deviceSn=....&deviceType=noah" to this. If it missing or the deviceSn is wrong you will get the response you are getting.

I used the curl command from above and it works.
